### ISSUE TITLE
the param of task.attempt in the base.config

### ISSUE THREAD

**Issue by bmbbms** [ewels/NGI-RNAseq#18]
sorry, when i used this config of task.attempt in base.config. i found it may not  take effect.so i do not know the use of task.attmpt in the config

**Comment by ewels** [comment]
Hi @bmbbms,

In nextflow, `task.attempt` is used when a task hits an error and is retired. You can read about it here: https://www.nextflow.io/docs/latest/process.html#dynamic-computing-resources

So, when everything is going well, there will be no errors and each task will be on it's first attempt. `task.attempt` will be `1` and the resources will be multiplied by `1` and not change. However, if a task fails with an acceptable error code that indicates that it ran out of time or resources, it will be retried. `task.attempt` will then be `2` and the requested resources will be doubled.

I hope this makes sense!

Phil

**Comment by bmbbms** [comment]
oh,thank you very much . i have known  the use of this param.
